### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by hasecilu**
Bring some Polish and German translations.

Tried to test but

image

### CODE REVIEW

**Comment by APEbbers** [comment]
Hi, I've fixed the problem and merged your PR.

It should work now

**Comment by hasecilu** [comment]
Hi, it doesn't get the errror at startup but when trying to open the "Ribbon layout"

image

**Comment by APEbbers** [comment]
Hi,

It should work again. I had to revert back due to a bug and overlooked this change

**Comment by hasecilu** [comment]
Mmm, tested again but now there are new erroos at startup

image

and trying to open the Ribbon layuot

image


I guess there is some WIP

**Comment by APEbbers** [comment]
HI,

I'm indeed working on some bugfixes. But these problems should be fixed now. 
You might switch off debug mode though. Currently there are a lot of warnings which have to be sorted

**Comment by hasecilu** [comment]
That did the trick, thanks!

**Pull request merged**
