### PR TITLE
Add icons that follow FreeCAD guidelines

### LINKED ISSUE #61: Icons are not visible on dark theme
2024-10-28-153614_hyprshot

### LINKED ISSUE #66: Names of toolbars are not being translated
A lot of built-in and external WB have been translated, including toolbar names. The names' translations are not shown in the ribbon. All this strings should be using the "Workbench" context but some external WB can have something different.

image

### LINKED ISSUE #75: Selected workbench name not readable on dark theme
Hard to read. I'm using OpenDark theme. The tabs from the opened documents don't have this problem. Bold and white would be OK

image

```
OS: Arch Linux (Hyprland/hyprland/wayland)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.36460 +2644 (Git)
Build type: Release
Branch: test/prs
Hash: 143c5f72ac69ac10c2eb7391b4afc114609bf9ec
Python 3.12.7, Qt 6.8.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * FreeGrid 2.0.1
  * StemfieWB 0.2.0
  * OpenTheme 2024.9.1
  * FreeCAD-Ribbon 1.3.8
```

### PR DESCRIPTION
**Pull request by hasecilu**
Maybe in the future some icons from PieMenu addon can also be useful here.

Are there more icons visible to user?

https://wiki.freecad.org/Artwork_Guidelines

2024-10-28-153748_hyprshot

Edit: I don't know why AppImage (latest weekly build) shows red outline
Edit2: Force-push to remove extra file.

image

Fix #61

### CODE REVIEW

**Comment by APEbbers** [comment]
Hi, Thanks for the update. I will look into this first before i merge the PR. I do agree that the standard icons from the pyqtribbon package must be improved. However, I thinking about a solution that makes that makes it easy to set the icons per FreeCAD theme and must be easy to update when a new theme is published. 

it will probally a dict or json file with the information needed to set the correct icons.

I also try to avoid changing the packages to much, because the are downloads from PyPi. When these are changed a lot, an update to a newer version of these packages will be a lot of work.

In my Develop branch, i've successfully changed the icons for the scrollbuttons (FCBinding.py):
image

kind regards

**Comment by hasecilu** [comment]
Cool, since the package is embedded, would be possible to migrate to have it as a dependency on the package.xml file?
I think I'll check the develop branch more often.

**Comment by APEbbers** [comment]
I had the package as a dependency first, but some people had issues installing it. The addon-manager didn't install it and people had to install the package manually. So for the time being the package is embedded. 

But I hope to find the cause and solve the issue in the future.

If you are interested. I've created a first implementation of the icon method per FreeCAD theme in the Develop branche.

**Comment by APEbbers** [comment]
Icons are added manually in the develop branch

**Pull request closed without merging**
