### PR TITLE
73 workbench buttons are not visible version 100rc2

### LINKED ISSUE #73: Workbench buttons are not visible ( Version 1.0.0.RC2 )
### Information
Version: 1.0.0.RC2 ( AppImage )
OS: Linux Mint 22 ( Cinnamon )
Installed Addons: OpenTheme

### Problem
When trying to install the theme and use it, the workbenches are missing and an empty space is where they are supposed to be. The only way to appear them is to modify the size of the small buttons to something like 30-50 to see them using Customize... -> Ribbon Preferences.

image

Additionally, I do not know if this is a bug but there isn't an option to change the size of big icons, only for small and medium sized ones.

### PR DESCRIPTION
**Pull request by APEbbers**

### CODE REVIEW

**Comment by APEbbers** [comment]
Hi,

Have a fix. The buttons on top won't change with the icons on the ribbon for now. I'm planning an overall UI improvement with extra settings. One of them will be related to the tabbar and quicktoolbar sizes and fonts.

kind regards

**Comment by hasecilu** [comment]
Hi, it seems something went wrong, the merge of this PR makes the ribbon to not load.

image

**Comment by APEbbers** [comment]
I forgot the uncomment imports. version 1.3.9.1 should work now

**Comment by hasecilu** [comment]
Working now, thanks.

**Pull request merged**
